#!/bin/bash

set -xe
echo "Running pre commit git hook"

repos=(1-networks/environments/project* 2-firewall-rules/environments/project* 3-vmseries/environments/project* 4-lbs/environments/trust 4-lbs/environments/untrust 5-app1/environments/dev)
for repo in ${repos[*]}
do
    pushd "$repo"
    terraform fmt
    terraform-docs markdown table . > README.md
    popd
done

