project_id="ngfw-299010"
backend = "https://www.googleapis.com/compute/v1/projects/ngfw-299010/zones/us-east4-a/instanceGroups/umig-vmseries"
network = "vpc-trust"
subnet = "sb-trust-us-east4"
network_self_link = "https://www.googleapis.com/compute/v1/projects/ngfw-299010/global/networks/vpc-trust"
region = "us-east4"
terraform_service_account = "sa-to-impersoante@ngfw-299010.iam.gserviceaccount.com"