project_id                = "ngfw1-301708"
backend                   = "https://www.googleapis.com/compute/v1/projects/ngfw1-301708/zones/us-east4-a/instanceGroups/umig-vmseries"
network                   = "vpc-trust"
subnet                    = "sb-trust-us-east4"
network_self_link         = "https://www.googleapis.com/compute/v1/projects/ngfw1-301708/global/networks/vpc-trust"
region                    = "us-east4"
terraform_service_account = "impersonate-me@ngfw1-301708.iam.gserviceaccount.com"
